### ISSUE TITLE
Bytes/BytesMut should not auto derive PartialEq

### ISSUE THREAD

**Issue by gatoWololo** [demikernel/catnip#12]
After the latest changes I'm getting an error:
```
Testing started at 12:36 PM ...
    Finished test [unoptimized + debuginfo] target(s) in 0.22s
     Running unittests (target/debug/deps/catnip-f4c694d71fb51b58)


Left:  Bytes([90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90])
Right: Bytes([90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90])
<Click to see difference>

thread 'protocols::tcp::tests::test_connect' panicked at 'assertion failed: `(left == right)`
  left: `Bytes([90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90])`,
 right: `Bytes([90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90])`', src/protocols/tcp/tests/mod.rs:71:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /home/gatowololo/.rustup/toolchains/nightly-2021-05-10-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:117:5
   4: catnip::protocols::tcp::tests::test_connect
             at ./src/protocols/tcp/tests/mod.rs:71:5
   5: catnip::protocols::tcp::tests::test_connect::{{closure}}
             at ./src/protocols/tcp/tests/mod.rs:27:1
   6: core::ops::function::FnOnce::call_once
             at /home/gatowololo/.rustup/toolchains/nightly-2021-05-10-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: test failed, to rerun pass '-p catnip --lib'

Process finished with exit code 101
```
We fail at:
```rust
assert_eq!(received_buf, buf);
```

Long story short. We have `#[derive(PartialEq)]` for both `Bytes` and `BytesMut`. This is actually not what we want since we only want to compare the data not the internal fields. This is why this test now fails. From my debugger I can see the `offset` field is different between `received_buf` and `buf`. We should implement PartialEq ourselves again, only comparing the values.

**Comment by ppenna** [comment]
@gatoWololo could you fix this?
